global spec_gamma_market_vars "gamma"
global spec_gamma_file_suffix "gamma"
global spec_original_market_vars "mmc cbo942d"
global spec_original_file_suffix "mmc_cbo942d"
global spec_gamma1_market_vars "gamma1"
global spec_gamma1_file_suffix "gamma1"
global spec_gamma_mcmc_market_vars "gamma_mcmc"
global spec_gamma_mcmc_file_suffix "gamma_mcmc"
global spec_gamma1_mcmc_market_vars "gamma1_mcmc"
global spec_gamma1_mcmc_file_suffix "gamma1_mcmc"
global spec_gamma_7500_market_vars "gamma_7500"
global spec_gamma_7500_file_suffix "gamma_7500"
global spec_gamma1_7500_market_vars "gamma1_7500"
global spec_gamma1_7500_file_suffix "gamma1_7500"
